/**
 * hrops.ts — PRD v2.1 WS-3 Nigerian HR rituals (FR-086, FR-087, FR-088).
 *
 * Confirmation and queries are formal artifacts of Nigerian employment practice,
 * not generic HR workflow. The platform already generates the EVIDENCE for the
 * first (30/60/90 completion, quality-of-hire, manager notes) and the GOVERNANCE
 * for the second (audit log, access control); these produce the ARTIFACTS.
 *
 * Governance carried from v2.0 and tightened by v2.1 §2.2:
 *  · The AI drafts and summarises. It never recommends a sanction (FR-088).
 *  · Disciplinary data is the most sensitive surface the platform has held —
 *    access is restricted to HR and the concerned line of management, every
 *    access is logged, and a DPIA gates GA on real employee data.
 *  · Case outcomes reach the attrition model only in aggregated, permissioned form.
 */
import type { PfTone } from "@/components/os/ui";

/* ------------------------------- FR-086 ------------------------------------ */

export type LetterKind =
  | "Employment confirmation" | "Embassy / visa introduction" | "Bank reference"
  | "Promotion" | "Probation confirmation";

export type LetterTemplate = {
  kind: LetterKind; icon: string; blurb: string;
  /** Fields the AI fills straight off the person record — no re-keying. */
  fills: string[];
  slaHours: number;
};

/** The letters Nigerian HR actually issues — not a generic document builder. */
export const LETTER_TEMPLATES: LetterTemplate[] = [
  { kind: "Employment confirmation", icon: "file", blurb: "Confirms role, grade, start date and that employment is current. The most-requested letter, by a distance.", fills: ["Full name", "Role & grade", "Start date", "Employment status"], slaHours: 24 },
  { kind: "Embassy / visa introduction", icon: "paperplane", blurb: "Addressed to a named mission, confirming employment, leave dates and intent to return.", fills: ["Full name", "Role", "Approved leave dates", "Return date"], slaHours: 24 },
  { kind: "Bank reference", icon: "wallet", blurb: "For loan or account applications. States employment and tenure; never states salary unless HR adds it explicitly.", fills: ["Full name", "Role", "Tenure", "Employment status"], slaHours: 24 },
  { kind: "Promotion", icon: "arrowup", blurb: "Issued on a grade change — pulls the effective date and new grade from the record.", fills: ["Full name", "Old grade", "New grade", "Effective date"], slaHours: 24 },
  { kind: "Probation confirmation", icon: "check", blurb: "Generated by the FR-087 confirmation decision rather than requested by hand.", fills: ["Full name", "Probation end", "Decision", "Effective date"], slaHours: 24 },
];

export type LetterState = "Requested" | "Drafted" | "Approved" | "Issued" | "Declined";

export type LetterRequest = {
  id: string; workerId: string; subject: string; kind: LetterKind;
  state: LetterState; requested: string; issued?: string;
  /** Present once issued — the QR resolves to the public verification page. */
  token?: string;
  addressedTo?: string;
  hoursElapsed: number;
  draft?: string;
};

export const LETTER_REQUESTS: LetterRequest[] = [
  {
    id: "LT-118", workerId: "E-0214", subject: "Amara Okonkwo", kind: "Employment confirmation",
    state: "Issued", requested: "Aug 26 · 09:12", issued: "Aug 26 · 14:40", token: "HB-7K2Q-9F4L", hoursElapsed: 5,
    draft: "This is to confirm that Amara Okonkwo has been employed by Unrealabs Limited as a Senior Software Engineer (Grade L5) since November 2023, and remains in our employment as at the date of this letter.",
  },
  {
    id: "LT-117", workerId: "E-0187", subject: "Ngozi Obi", kind: "Bank reference",
    state: "Issued", requested: "Aug 12 · 11:03", issued: "Aug 12 · 16:55", token: "HB-3M8T-1P0R", hoursElapsed: 6,
    addressedTo: "Guaranty Trust Bank",
    draft: "This is to confirm that Ngozi Obi is employed by Unrealabs Limited as a Finance Analyst and has been in our employment for 2 years. This reference is issued at the employee's request and states no salary information.",
  },
  {
    id: "LT-121", workerId: "E-0231", subject: "Emeka Nwosu", kind: "Embassy / visa introduction",
    state: "Drafted", requested: "Aug 27 · 08:20", hoursElapsed: 3, addressedTo: "Embassy of the Netherlands, Abuja",
    draft: "This is to introduce Emeka Nwosu, Field Operations Lead at Unrealabs Limited since July 2022. Mr Nwosu has been granted approved annual leave from 2 to 15 September 2026 and is expected to resume duty on 16 September 2026.",
  },
  { id: "LT-122", workerId: "E-0129", subject: "Halima Sule", kind: "Employment confirmation", state: "Requested", requested: "Aug 27 · 10:05", hoursElapsed: 1 },
];

export const letterSla = (r: LetterRequest): { tone: PfTone; label: string } => {
  if (r.state === "Issued") return { tone: "green", label: `Issued in ${r.hoursElapsed}h` };
  if (r.hoursElapsed >= 24) return { tone: "red", label: `${r.hoursElapsed}h — SLA breached` };
  if (r.hoursElapsed >= 18) return { tone: "yellow", label: `${24 - r.hoursElapsed}h left` };
  return { tone: "blue", label: `${24 - r.hoursElapsed}h left` };
};

/* ------------------------------- FR-087 ------------------------------------ */

export type ConfirmationDecision = "confirm" | "extend" | "exit";

export type ConfirmationCase = {
  id: string; workerId: string; subject: string; role: string; init: string; tone: string;
  startedAt: string; months: 3 | 6; endsAt: string; daysToEnd: number;
  state: "Running" | "Evidence ready" | "Decided";
  decision?: ConfirmationDecision; effectiveDate?: string; reasons?: string;
  /** Auto-compiled — the point of FR-087 is that nobody assembles this by hand. */
  evidence: { plan30_60_90: string; qoh?: string; managerNotes: string; goals: string };
};

export const CONFIRMATION_CASES: ConfirmationCase[] = [
  {
    id: "CF-31", workerId: "E-0243", subject: "Chidi Okeke", role: "Backend Engineer", init: "CO", tone: "#E81E17",
    startedAt: "Jul 1, 2026", months: 3, endsAt: "Oct 1, 2026", daysToEnd: 35, state: "Evidence ready",
    evidence: {
      plan30_60_90: "30-day complete · 60-day in progress (2 of 3 milestones)",
      qoh: "Day-90 score pending — first read Oct 1",
      managerNotes: "Productive on the Go services inside a month; pairing with Amara went well.",
      goals: "First goals drafted and agreed in the 30-day check-in.",
    },
  },
  {
    id: "CF-29", workerId: "E-0198", subject: "Adaeze Okafor", role: "Senior Product Designer", init: "AD", tone: "#16B364",
    startedAt: "May 20, 2026", months: 6, endsAt: "Nov 20, 2026", daysToEnd: 85, state: "Running",
    evidence: {
      plan30_60_90: "30- and 60-day complete · 90-day opens Aug 18",
      managerNotes: "Owns the review-cycle experience end to end (O-03, 71%).",
      goals: "Individual objective on track.",
    },
  },
  {
    id: "CF-27", workerId: "W-3304", subject: "Chiamaka Nwosu", role: "HSE Intern (NYSC)", init: "CN", tone: "#16B364",
    startedAt: "Mar 2, 2026", months: 6, endsAt: "Sep 2, 2026", daysToEnd: 6, state: "Evidence ready",
    evidence: {
      plan30_60_90: "Service-year plan complete",
      managerNotes: "Ran the toolbox-talk audit unsupervised for the last two months.",
      goals: "PPA objectives met.",
    },
  },
];

/* ------------------------------- FR-088 ------------------------------------ */

export type CaseStage = "Query issued" | "Response received" | "Panel" | "Outcome" | "Closed";

export const CASE_STAGES: CaseStage[] = ["Query issued", "Response received", "Panel", "Outcome", "Closed"];

export type DisciplinaryCase = {
  id: string; workerId: string; subject: string; init: string; tone: string; role: string;
  opened: string; stage: CaseStage; category: string;
  /** AI-drafted, tone-guarded. The model never proposes the sanction. */
  queryDraft: string;
  response?: string; responseAt?: string;
  panelNotes?: string;
  outcome?: string; sanction?: string; sanctionAt?: string;
  retention: string;
  /** Every access is logged — this renders in the case's own audit strip. */
  accessLog: { at: string; who: string; action: string }[];
};

export const DISCIPLINARY_CASES: DisciplinaryCase[] = [
  {
    id: "DC-14", workerId: "W-3305", subject: "Musa Bello", init: "MB", tone: "#475569", role: "Scaffolder",
    opened: "Aug 18, 2026", stage: "Response received", category: "Attendance",
    queryDraft:
      "You are required to explain your absence from duty on 5, 7 and 11 August 2026, on which dates no clock-in was recorded and no prior leave was approved. Please respond in writing within 48 hours of receipt. This query is issued to establish the facts; no conclusion has been drawn.",
    response:
      "I was unable to reach the terminal on those dates because the crew boat did not run. I reported this to the materials controller each morning by phone.",
    responseAt: "Aug 20, 2026",
    retention: "Retain 6 years from closure, then destroy",
    accessLog: [
      { at: "Aug 20 · 09:41", who: "People Ops · Funke Adebayo", action: "opened case" },
      { at: "Aug 20 · 09:44", who: "People Ops · Funke Adebayo", action: "recorded response" },
      { at: "Aug 21 · 14:02", who: "Field Operations · Ibrahim Sani", action: "viewed case (line manager)" },
    ],
  },
  {
    id: "DC-12", workerId: "E-0092", subject: "Tunde Bakare", init: "TB", tone: "#EBA308", role: "Product Manager",
    opened: "Jun 02, 2026", stage: "Closed", category: "Conduct",
    queryDraft: "You are required to explain the circumstances described in the attached report. Please respond in writing within 48 hours of receipt.",
    response: "Provided in writing on 4 June with supporting correspondence.",
    responseAt: "Jun 04, 2026",
    panelNotes: "Panel accepted the explanation. No further action; note placed on file for 12 months.",
    outcome: "No further action", sanction: "None", sanctionAt: "Jun 11, 2026",
    retention: "Retain 6 years from closure, then destroy",
    accessLog: [
      { at: "Jun 11 · 16:20", who: "People Ops · Funke Adebayo", action: "recorded outcome" },
      { at: "Jul 02 · 10:15", who: "People Ops · Funke Adebayo", action: "viewed case" },
    ],
  },
];

/** FR-088: outcomes reach the attrition model ONLY aggregated and permissioned. */
export const caseAggregate = () => {
  const open = DISCIPLINARY_CASES.filter((c) => c.stage !== "Closed").length;
  return {
    open, closed: DISCIPLINARY_CASES.length - open,
    byCategory: [...new Set(DISCIPLINARY_CASES.map((c) => c.category))].map((cat) => ({
      cat, n: DISCIPLINARY_CASES.filter((c) => c.category === cat).length,
    })),
    modelNote: "Only these counts reach the attrition feature set. No case narrative, no named subject, no sanction detail.",
  };
};
